import { StyleSheet, Platform } from 'react-native';
import { IMAGE_BANNER_HEIGHT } from '../../../components/ImageBanner';

import themeVariables from '../../../styles/theme';
import sectionBaseStyles from '../common/sectionBaseStyles';
import { detailCardOverlay, detailCardTitle, detailCardSubtitle, detailCardContent } from '../common/detailCardLayout';

const styles = StyleSheet.create({
  card: {
    width: '100%',
    backgroundColor: 'red',
    elevation: 0,
    margin: 0,
    borderRadius: 16,
    overflow: 'hidden',
  },
  banner: { width: '100%', height: IMAGE_BANNER_HEIGHT, borderRadius: 0 },
  overlayCard: {
    ...detailCardOverlay,
  },
  titleBlock: { fontWeight: 'bold', alignItems: 'center' },
  cardTitleText: {
    ...detailCardTitle,
  },
  cardSubtitleText: {
    ...detailCardSubtitle,
  },
  cardContent: {
    ...detailCardContent,
  },
  headerInfoContainer: {
    alignItems: 'center',
    marginVertical: 8,
  },
  headerInfoText: {
    fontSize: 16,
    color: '#666',
  },
  divider: {
    ...sectionBaseStyles.sectionDivider,
  },
  mapTitle: {
    ...sectionBaseStyles.sectionTitle,
  },
  carouselContent: {
    paddingLeft: 4,
  },
  carouselTitle: {
    color: themeVariables.blackColor,
    fontSize: 20,
    fontWeight: '600',
    marginTop: 14,
    marginBottom: 14,
  },
  userListContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  userItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
    marginBottom: 6,
  },
  avatarName: {
    fontSize: 12,
    color: '#666',
    marginLeft: 4,
  },
  sessionCard: {
    backgroundColor: themeVariables.whiteColor,
    padding: 8,
    marginRight: 10,
    alignItems: 'center',
    minWidth: 100,
  },
  sessionCardDate: {
    fontSize: 14,
    fontWeight: '500',
    color: themeVariables.primaryColor,
    marginBottom: 4,
    textAlign: 'left',
  },
  sessionCardTime: {
    fontSize: 12,
    color: '#666',
  },
  sessionStatusChip: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: themeVariables.primaryColor,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  sessionStatusText: {
    color: themeVariables.whiteColor,
    fontSize: 10,
    fontWeight: '600',
  },
  sessionInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    width: '100%',
  },
  sessionSection: {
    flex: 1,
    alignItems: 'center',
  },
  sessionSectionTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: themeVariables.blackColor,
    marginBottom: 4,
    textAlign: 'center',
  },
  sessionInfoText: {
    fontSize: 12,
    color: '#666',
  },
  factRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 14,
  },
  factBox: { flex: 1, alignItems: 'center' },
  factLabel: { fontSize: 11, color: '#666', marginTop: 4, textAlign: 'center', width: Platform.select({ android: 150 })},
  factValue: {
    fontSize: 14,
    fontWeight: '600',
    color: themeVariables.blackColor,
    textAlign: 'center',
    width: Platform.select({ android: 150 }),
  },
  linkText: {
    color: themeVariables.primaryColor,
    textDecorationLine: 'underline',
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 14,
  },
  detailCell: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  detailIcon: { marginBottom: 6 },
  detailLabel: {
    fontSize: 11,
    color: '#666',
    marginBottom: 4,
    textAlign: 'center',
    width: Platform.select({ android: 65 }),
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#312783',
    marginBottom: 4,
    textAlign: 'center',
    width: Platform.select({ android: 65 }),
  },
  detailSub: {
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
  },
  sectionContainer: {
    ...sectionBaseStyles.sectionContainer,
  },
  sectionTitle: {
    ...sectionBaseStyles.sectionTitle,
  },
  avatarsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#fff',
  },
  mapContainer: {
    width: '100%',
    height: 200,
    borderRadius: 12,
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 20,
    overflow: 'hidden',
    marginBottom: 8,
  },
  mapWrapper: {
    width: '100%',
    height: 300,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    overflow: 'hidden',
    marginBottom: 8,
  },
  mapLoader: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  hostAddressContainer: {
    alignSelf: 'flex-start',
    marginVertical: 12,
  },
  hostAddressTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: themeVariables.blackColor,
    marginBottom: 4,
  },
  hostAddressSubtitle: {
    fontSize: 14,
    color: themeVariables.textColor || '#555',
  },
  onlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginVertical: 12,
  },
  titleWithTooltip: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  tooltipIconTarget: {
    padding: 6,
    marginLeft: 6,
  },
  tooltipBubble: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  tooltipPopoverText: {
    fontSize: 12,
    color: '#fff',
  },
  map: {
    width: '100%',
    height: '100%',
  },
  sideSection: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  dividerVertical: {
    width: 1,
    backgroundColor: '#ddd',
  },
  sessionCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 8,
  },
  sessionStatusInline: {
    backgroundColor: themeVariables.primaryColor,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  sessionStatusInlineText: {
    color: themeVariables.whiteColor,
    fontSize: 12,
    fontWeight: '600',
  },
  avatarNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  extraCount: {
    backgroundColor: '#666',
    justifyContent: 'center',
    alignItems: 'center',
  },
  extraCountText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    width: Platform.select({ android: 40 }),
  },
  modalList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  modalBadgeWrap: {
    width: 100,
    alignItems: 'center',
    margin: 8,
  },
  ctaButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: '#eee',
    marginRight: 8,
    marginTop: 6,
  },
  ctaText: { fontSize: 14, fontWeight: '600' },
  requestButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: themeVariables.primaryColor,
    marginTop: 8,
  },
  requestButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: themeVariables.whiteColor,
    marginLeft: 6,
  },
  guidelinesText: {
    fontSize: 14,
    color: '#666',
    marginTop: 8,
    marginBottom: 12,
    alignSelf: 'flex-start',
  },
  curriculumBox: {
    width: '100%',
    borderRadius: 16,
    backgroundColor: themeVariables.primaryColor + '0D',
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginTop: 8,
  },
  curriculumRowContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginVertical: 6,
  },
  curriculumLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: themeVariables.textColor || '#333',
    width: 80,
  },
  curriculumValue: {
    flex: 1,
    fontSize: 14,
    color: themeVariables.textColor || '#444',
    marginLeft: 16,
  },
  curriculumDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#ddd',
    marginVertical: 6,
  },
  footerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    paddingBottom: 36,
    backgroundColor: themeVariables.whiteColor || '#fff',
  },
  formLink: {
    paddingVertical: 6,
    alignSelf: 'flex-start',
  },
  formLinkText: {
    fontSize: 14,
    color: themeVariables.primaryColor,
    textDecorationLine: 'underline',
  },
  statusChip: {
    position: 'absolute',
    top: 48,
    right: 20,
    backgroundColor: themeVariables.primaryColor,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    zIndex: 10,
  },
  statusChipText: {
    color: themeVariables.whiteColor,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    width: Platform.select({ android: 100 }),
  },
});

export default styles;
